### PR TITLE
V0.15.0 update

### PR DESCRIPTION
**Pull request by sigma-andex**

### CODE REVIEW

**Comment by fsoikin** [comment]
@sigma-andex could you please also update bower.json with the new versions, so downstream libraries can have correct resolutions?

**Comment by sigma-andex** [comment]
> @sigma-andex could you please also update bower.json with the new versions, so downstream libraries can have correct resolutions?

bower.json is updated!?

**Comment by JordanMartinez** [comment]
LGTM

**Comment by garyb** [comment]
Thanks! I'll fix the build separately.

**Pull request merged**
