### PR TITLE
Add `showAny`

### PR DESCRIPTION
**Pull request by colehaus**

### CODE REVIEW

**Comment by garyb** [comment]
What's the thinking with this one? I'm slightly reluctant to add it since it's basically an arbitrary to-string function. Although I guess it still has the warning, at least.

**Comment by colehaus** [comment]
The use case I have in mind is for when I put in `unsafeCrashWith` in branches that should never be hit while invariants aren't violated (e.g. I want to turn a non-empty `List` into `NonEmpty List` and I know it's safe but can't prove it to the compiler). If, somehow, I'm wrong about the invariants holding and we do crash, it'd be useful to be able to see that data and collect it in logs, etc. Especially since (due to the fact that they're unexpected violations of invariants) these crashes may be hard to repro. 

The obvious remedy of just `show`ing the data isn't a great one for library code because it incurs a `Show` constraint on your data which may not be ideal for all library users. Furthermore, if the crashy function is deep in the library, a `Show` constraint on it propagates throughout library type signatures which can clutter things.

In case it helps understand what I'm getting at: I think the first best solution would be something like a first class conditional constraint (a la https://github.com/mikeizbicki/ifcxt) so the function can `show` if a `Show` instance is available and not if it isn't. But in the absence of that, this seems like an okay solution to me.

**Comment by garyb** [comment]
I'd suggest we make a variation of `unsafeCrashWith` that does this then perhaps? You probably wouldn't want to use this function as it is, because doing so will raise the `Debug.Trace usage` warning where you use it. Also this module in general is just intended as a dev-dependency kinda thing, whereas `-partial` is a "real" library :smile:

**Comment by colehaus** [comment]
Done.

**Pull request closed without merging**
